"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=qbc_0(q3lecp7y2gug=faug)7!cg^n96!#guk($+l7b1=sj0w'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'club'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'club' / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# ===================================
# MEDIA FILES CONFIGURATION
# ===================================

# Media files (User uploaded files)
# These are files uploaded by users (profile pictures, documents, etc.)

# URL that handles the media served from MEDIA_ROOT
# Example: http://localhost:8000/media/profile_pics/john_doe.jpg
MEDIA_URL = '/media/'

# Absolute filesystem path to the directory that will hold user-uploaded files
# Files will be stored in: project/media/
MEDIA_ROOT = BASE_DIR / 'media'

# Maximum upload file size (in bytes)
# 5MB = 5 * 1024 * 1024 bytes
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB

# Allowed image file extensions
ALLOWED_IMAGE_EXTENSIONS = ['.jpg', '.jpeg', '.png', '.gif', '.webp']

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ===================================
# EMAIL CONFIGURATION
# ===================================

# Email Backend Configuration
# For development: Console backend (prints emails to console)
# For production: SMTP backend (sends real emails)

# Development - Email prints to console
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Production - SMTP Configuration (commented out for development)
# Uncomment and configure these settings for production use
"""
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Gmail SMTP server
EMAIL_PORT = 587  # TLS port
EMAIL_USE_TLS = True  # Use TLS encryption
EMAIL_HOST_USER = 'your-email@gmail.com'  # Your email address
EMAIL_HOST_PASSWORD = 'your-app-password'  # App password (not regular password)
DEFAULT_FROM_EMAIL = 'Tennis Club <your-email@gmail.com>'
"""

# Default email settings
DEFAULT_FROM_EMAIL = 'Tennis Club <noreply@tennisclub.com>'
ADMINS = [('Admin', 'admin@tennisclub.com')]
MANAGERS = ADMINS

# Email timeout (in seconds)
EMAIL_TIMEOUT = 10


# ===================================
# AUTHENTICATION CONFIGURATION
# ===================================

# Login/Logout redirect URLs
LOGIN_URL = 'club:login'
LOGIN_REDIRECT_URL = 'club:main'
LOGOUT_REDIRECT_URL = 'club:main'
