# Generated by Django 6.0.1 on 2026-01-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='names',
            name='city',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='names',
            name='location',
            field=models.CharField(null=True),
        ),
    ]
