# Generated by Django 6.0.1 on 2026-01-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_names_city_names_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='names',
            name='date_joined',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='names',
            name='city',
            field=models.CharField(default='Not specified', max_length=250),
        ),
        migrations.AlterField(
            model_name='names',
            name='firstname',
            field=models.CharField(default='Unknown', max_length=250),
        ),
        migrations.AlterField(
            model_name='names',
            name='lastname',
            field=models.CharField(default='Member', max_length=250),
        ),
        migrations.AlterField(
            model_name='names',
            name='location',
            field=models.CharField(default='Not specified', max_length=250),
        ),
    ]
