# Generated by Django 6.0.1 on 2026-02-01 16:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_names_date_joined_alter_names_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='names',
            name='date_started',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='names',
            name='date_updated',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='names',
            name='status',
            field=models.CharField(choices=[('NPL', 'Not_Played'), ('PL', 'Played')], default='NPL', max_length=4),
        ),
        migrations.AlterField(
            model_name='names',
            name='date_joined',
            field=models.DateField(auto_now_add=True),
        ),
    ]
