# Generated by Django 6.0.1 on 2026-02-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_names_date_started_names_date_updated_names_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='names',
            name='slug',
            field=models.SlugField(blank=True, max_length=500),
        ),
    ]
