# Generated by Django 6.0.1 on 2026-02-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_names_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='names',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, unique=True),
        ),
    ]
