# Generated by Django 6.0.1 on 2026-02-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_alter_names_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='names',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='names',
            name='phoneNumber',
            field=models.CharField(default='000-000-0000', max_length=15),
        ),
    ]
