# Generated by Django 6.0.1 on 2026-02-27 08:18

import club.file_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0007_names_email_names_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='names',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Upload a profile picture (JPG, PNG, GIF, WEBP - Max 5MB)', null=True, upload_to=club.file_utils.member_profile_picture_path, validators=[club.file_utils.validate_image_file]),
        ),
    ]
